=== krussan/jukebox/se.qxx.jukebox/JukeboxSettings.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="JukeboxListenerSettings">
    <xs:complexType>
      <xs:sequence>
      	<xs:element name="catalogs">
      		<xs:complexType>
      			<xs:sequence>
      				<xs:element maxOccurs="unbounded"
      					name="catalog">
      					<xs:complexType>
      						<xs:sequence>
      							<xs:element name="extensions">
      								<xs:complexType>
      									<xs:sequence>
      										<xs:element
      											maxOccurs="unbounded" name="extension">
      											<xs:complexType>
      												<xs:attribute
      													name="value" type="xs:string" use="required" />
      											</xs:complexType>
      										</xs:element>
      									</xs:sequence>
      								</xs:complexType>
      							</xs:element>
      						</xs:sequence>
      						<xs:attribute name="path" type="xs:string"
      							use="required" />
      						<xs:attribute name="includeSubdirectories"
      							type="xs:boolean" use="required" />
      						<xs:attribute name="vlcPath"
      							type="xs:string">
      						</xs:attribute>
      					</xs:complexType>
      				</xs:element>
      			</xs:sequence>
      		</xs:complexType>
      	</xs:element>
      	<xs:element name="subFinders">
      		<xs:complexType>
      			<xs:sequence>
      				<xs:element maxOccurs="unbounded"
      					name="subFinder">
      					<xs:complexType>
      						<xs:sequence>
      							<xs:element name="subFinderSettings"
      								maxOccurs="1" minOccurs="1">
      								<xs:complexType>
      									<xs:sequence>
      										<xs:element name="setting"
      											maxOccurs="unbounded" minOccurs="0">
      											<xs:complexType>
      												<xs:sequence>
      													<xs:element
      														name="key" type="xs:string">
      													</xs:element>
      													<xs:element
      														name="value" type="xs:string">
      													</xs:element>
      												</xs:sequence>
      											</xs:complexType>
      										</xs:element>
      									</xs:sequence>
      								</xs:complexType>

      							</xs:element>
      						</xs:sequence>
      						<xs:attribute name="class"
      							type="xs:string" use="required" />
      					</xs:complexType>
      				</xs:element>
      			</xs:sequence>
      			<xs:attribute name="subsPath" type="xs:string"
      				use="required" />
      		</xs:complexType>
      	</xs:element>
      	<xs:element name="stringSplitters">
      		<xs:complexType>
      			<xs:sequence>
      				<xs:element maxOccurs="unbounded"
      					name="splitter">
      					<xs:complexType>
      						<xs:sequence>
      							<xs:element name="regex"
      								type="xs:string">
      							</xs:element>
      						</xs:sequence>
      					</xs:complexType>
      				</xs:element>
      			</xs:sequence>
      		</xs:complexType>
      	</xs:element>
      	<xs:element name="tcpListener">
      		<xs:complexType>
      			<xs:sequence>
      				<xs:element name="port">
      					<xs:complexType>
      						<xs:attribute name="value"
      							type="xs:unsignedShort" use="required" />
      					</xs:complexType>
      				</xs:element>
      			</xs:sequence>
      		</xs:complexType>
      	</xs:element>
      	<xs:element name="vlc">
      		<xs:complexType>
      			<xs:sequence>
      				<xs:element name="server">
      					<xs:complexType>
      						<xs:sequence></xs:sequence>
      						<xs:attribute name="host"
      							type="xs:string">
      						</xs:attribute>
      						<xs:attribute name="port" type="xs:int">
      						</xs:attribute>
      						<xs:attribute name="subsPath"
      							type="xs:string">
      						</xs:attribute>
      					</xs:complexType></xs:element>
      			</xs:sequence>
      		</xs:complexType></xs:element>
      	<xs:element name="logs">
      		<xs:complexType>
      			<xs:sequence>
      				<xs:element name="log" minOccurs="0"
      					maxOccurs="unbounded">
      					<xs:complexType>
      						<xs:attribute name="type" type="xs:string"
      							use="required" />
      						<xs:attribute name="filename"
      							type="xs:string" use="optional" />
      						<xs:attribute name="level"
      							type="xs:string" use="required" />
      					</xs:complexType>
      				</xs:element>
      			</xs:sequence>
      		</xs:complexType>
      	</xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>



</xs:schema>

=== krussan/jukebox/se.qxx.jukebox/bin/se/qxx/jukebox/JukeboxSettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<JukeboxListenerSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="JukeboxSettings.xsd">
  <catalogs>
    <catalog includeSubdirectories="true" path="">
      <extensions>
        <extension value=""/>
      </extensions>
    </catalog>
  </catalogs>
  <subFinders>
    <subFinder assembly="" type=""/>
  </subFinders>
  <stringSplitters>
    <splitter regex=""/>
  </stringSplitters>
  <tcpListener>
    <port value="0"/>
  </tcpListener>
  <logs>
  	<log type="file" filename="/var/log/jukebox.log" leve="DEBUG" />
  </logs>
</JukeboxListenerSettings>
