=== krussan/jukebox/se.qxx.jukebox/parser.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.qxx.se/jukebox/parser" xmlns:tns="http://www.qxx.se/jukebox/parser" elementFormDefault="qualified">
    <element name="parser">
    	<complexType>
    		<sequence>
    			<element name="keywords">
    				<complexType>
    					<sequence>
    						<element name="type">
    							<complexType>
    								<sequence>
    									<element name="word"
    										type="tns:wordType" maxOccurs="unbounded" minOccurs="0">
    									</element>
    								</sequence>
    							</complexType>
    						</element>
    						<element name="format">
    							<complexType>
    								<sequence>
    									<element name="word"
    										type="tns:wordType" maxOccurs="unbounded" minOccurs="0">
    									</element>
    								</sequence>
    							</complexType>
    						</element>
    						<element name="sound">
    							<complexType>
    								<sequence>
    									<element name="word"
    										type="tns:wordType" maxOccurs="unbounded" minOccurs="0">
    									</element>
    								</sequence>
    							</complexType>
    						</element>
    						<element name="language">
    							<complexType>
    								<sequence>
    									<element name="word"
    										type="tns:wordType" maxOccurs="unbounded" minOccurs="0">
    									</element>
    								</sequence>
    							</complexType>
    						</element>
    						<element name="other">
    							<complexType>
    								<sequence>
    									<element name="word"
    										type="tns:wordType" maxOccurs="unbounded" minOccurs="0">
    									</element>
    								</sequence>
    							</complexType>
    						</element>
    					</sequence>

    				</complexType>
    			</element>
    		</sequence>
    	</complexType>
    </element>

    <complexType name="wordType">
    	<attribute name="key" type="string"></attribute>
    </complexType>
</schema>

=== krussan/jukebox/se.qxx.jukebox/parser.xml
<?xml version="1.0" encoding="UTF-8"?>
<parser xmlns="http://www.qxx.se/jukebox/parser" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.qxx.se/jukebox/parser parser.xsd ">
  <keywords>
    <type>
        <word key="480p" />
        <word key="720p" />
        <word key="1080p" />
        <word key="PPVRIP" />
        <word key="BRRip" />
        <word key="DVDRip" />
        <word key="VODRip" />
        <word key="HDRip" />
        <word key="WEBRip" />
        <word key="DVDSCREENER" />
        <word key="DVDSCR" />
        <word key="TS" />
        <word key="PPV" />
        <word key="Bluray" />
        <word key="BDRip" />
        <word key="HDTV" />        
    </type>
    <format>
        <word key="XviD" />
        <word key="IFLIX" />
        <word key="x264" />
        <word key="h264" />
    </format>
    <sound>
        <word key="AC3" />
        <word key="aac" />
        <word key="ac3pt" />
    </sound>
    <language>
        <word key="Eng" />
        <word key="SWEDISH" />
        <word key="SWE" />
        <word key="SWESUB" />
        <word key="German" />
        <word key="en" />
        <word key="de" />
    </language>
    <other>
        <word key="REPACK" />
        <word key="V2" />
        <word key="M777" />
        <word key="READNFO" />
        <word key="HQ" />
        <word key="LIMITED" />
        <word key="MD" />
        <word key="i2p" />
        <word key="EXTENDED" />
        <word key="DC" />        
    </other>
  </keywords>
</parser>
