=== krussan/jukebox/se.qxx.jukebox/src/main/xsds/imdb.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    attributeFormDefault="unqualified"
    elementFormDefault="qualified">

    <xs:element name="imdb">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element name="settings" maxOccurs="1"
    				minOccurs="1">
    				<xs:complexType>
    					<xs:attribute name="sleepSecondsMin"
    						type="xs:int" use="required">
    					</xs:attribute>
    					<xs:attribute name="sleepSecondsMax"
    						type="xs:int" use="required">
    					</xs:attribute>
    					<xs:attribute name="debug" type="xs:boolean"
    						default="false">
    					</xs:attribute>
    				</xs:complexType>
    			</xs:element>
    			<xs:element name="title" maxOccurs="1" minOccurs="1">
    				<xs:complexType>
    					<xs:sequence>
    					</xs:sequence>
    					<xs:attribute name="preferredLanguage"
    						type="xs:string">
    					</xs:attribute>
    					<xs:attribute name="useOriginalIfExists"
    						type="xs:boolean">
    					</xs:attribute>
    				</xs:complexType>
    			</xs:element>
    			<xs:element name="searchUrl" type="xs:string"
    				maxOccurs="1" minOccurs="1">
    			</xs:element>
    			<xs:element name="datePatterns" maxOccurs="1" minOccurs="0">
    				<xs:complexType>
    					<xs:sequence>
    						<xs:element name="pattern"
    							type="xs:string" maxOccurs="unbounded" minOccurs="0">
    						</xs:element>
    					</xs:sequence>
    				</xs:complexType></xs:element>
    		</xs:sequence>
    	</xs:complexType></xs:element>

    <xs:simpleType name="InfoPatternType">
    	<xs:restriction base="xs:string">
    		<xs:enumeration value="title" />
    		<xs:enumeration value="poster" />
    		<xs:enumeration value="story" />
    		<xs:enumeration value="year" />
    		<xs:enumeration value="rating" />
    		<xs:enumeration value="genres" />
    		<xs:enumeration value="duration" />
    		<xs:enumeration value="director" />
    		<xs:enumeration value="seasons" />
    		<xs:enumeration value="value" />
    		<xs:enumeration value="firstAirDate" />
    	</xs:restriction>
    </xs:simpleType>
</xs:schema>

=== krussan/jukebox/se.qxx.jukebox/imdb.xml
<?xml version="1.0" encoding="UTF-8"?>
<imdb xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="imdb.xsd">
    <settings
        sleepSecondsMin="20"
        sleepSecondsMax="30"
        debug="false"
    />
    <title
        preferredLanguage="default"
        useOriginalIfExists="true">
        
    </title>
    
    <searchUrl><![CDATA[https://www.imdb.com/find?s=tt&q=%%TITLE%%]]></searchUrl>
    
    <datePatterns>
        <pattern><![CDATA[dd MMM yyyy]]></pattern>
        <pattern><![CDATA[dd MMM. yyyy]]></pattern>
        <pattern><![CDATA[dd MMMM yyyy]]></pattern>
        <pattern><![CDATA[MMM. dd, yyyy]]></pattern>
        <pattern><![CDATA[yyyy-MM-dd]]></pattern>
    </datePatterns>
</imdb>
